### ISSUE TITLE
Network Xing

### ISSUE THREAD

**Issue by trehehaeuser** [ronalfy/highlight-and-share#14]
Hi, can you add Xing (European Business Network) to your plugin, please? Best, Thomas

https://www.xing.com/

**Comment by trehehaeuser** [comment]
Hi Ronald,

thank you for you message.

How much would it cost?

Best,

Thomas

**Comment by ronalfy** [comment]
Let me do some research so I can give an accurate estimate.

**Comment by ronalfy** [comment]
Can you email me at ronalfy @ gmail and we’ll work out a deal. I looked at the docs and believe this is possible using Highlight and Share.

https://dev.xing.com/plugins/share_button/docs

**Comment by ronalfy** [comment]
HAS now has XING support.

**Comment by trehehaeuser** [comment]
Good Morning Ronald,

you*re my hero of the day! Fantastic work!

Many greetings from Germany. You're always welcome to a cup of tea (or two, three ...).

Best, 
Thomas
