### ISSUE TITLE
Plugin action only on blog pages

### ISSUE THREAD

**Issue by XpucTiHu** [ronalfy/highlight-and-share#15]
Hi, Thank you very much for your work. Tell me please how can I configure the plugin so that it works only on blog pages but not activated on the main and other pages of the site? thank you

**Comment by ronalfy** [comment]
Something like this should work:

```php
add_filter( 'has_enable_content', function( $default ) {
    if ( is_single() ) return true;
    return false;
} );
```

**Comment by XpucTiHu** [comment]
Thank you very much for the answer
and where should I add it?

**Comment by ronalfy** [comment]
I'd place it in functions.php (http://www.wpbeginner.com/glossary/functions-php/) or a site-specific plugin( http://www.wpbeginner.com/beginners-guide/what-why-and-how-tos-of-creating-a-site-specific-wordpress-plugin/)
