### ISSUE TITLE
Support Whatshap

### ISSUE THREAD

**Issue by bianqui149** [ronalfy/highlight-and-share#16]
Hi ronald, awesome plugin, is there are a support for share in whatsapp?

**Comment by ronalfy** [comment]
@bianqui149 
If you can try out the latest master here, I have added in WhatsApp, but I need testers to make sure it's to your liking. Can you try it out and get back to me?

**Comment by bianqui149** [comment]
It's working fine the new addon!! Thanks for add whatshapp. Awesome plugin!
