### ISSUE TITLE
Support for LinkedIn, eMail and Groups

### ISSUE THREAD

**Issue by gman-tools** [ronalfy/highlight-and-share#5]
Cool plugin Ronald. Will be testing later in the week. Wondering if you have plans to get it working with LinkedIn and also Email., and also groups, both social groups - and eMail?

I think these would add a lot of professional and commercial engagement value.

Best,
G

**Comment by ronalfy** [comment]
These sound like cool features, with some more difficult to implement than others. 

Right now it's a matter of my time and ROI. The plugin is very lightly used atm: https://wordpress.org/plugins/highlight-and-share/stats/
