### ISSUE TITLE
Features request: save shared content

### ISSUE THREAD

**Issue by ventoh** [ronalfy/highlight-and-share#7]
Hello, i have feature request. It could be very useful if the shared notes could be saved in wordpress database. So when a page is loaded they can be showed. Similar to medium.com.
I can make a donation to support you implemenenting this feature.
Thank you

**Comment by ronalfy** [comment]
Sorry, this seems to be out of the scope of the plugin. The plugin is simply for sharing highlighted text via Twitter or sharing a page on Facebook. Front-end editing/commenting is another monster.
